config/routes.rb
Aggregate::Application.routes.draw do
  get    "feed"     => "social#index", :as => "feed"
  delete "auth/:id" => "authentications#destroy", :as => "destroy_auth"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  root :to => "index#index"

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :uid, :token, :secret, :expires_at
  belongs_to      :provider
  belongs_to      :user
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  attr_accessible :name
  has_many        :authentications
end

app/models/user.rb
require "feed_factory"

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me
  devise   :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

  has_many :authentications
  has_many :providers, :through => :authentications

  # Add new auth for current user
  def add_auth(omniauth)
    provider_id = Provider.find_by_name(omniauth.provider)
    params      = { :uid => omniauth.uid, :provider => provider_id }

    if omniauth.credentials
      params[:token]      = omniauth.credentials.token
      params[:secret]     = omniauth.credentials.secret
      params[:expires_at] = omniauth.credentials.expires_at
    end

    auth = authentications.create(params)
  end

  # Get missing providers
  def missing_providers
    all_auth     = Provider.all.collect  { |a| a.name }
    current_auth = providers.collect     { |a| a.name }

    # Just return difference between all an current
    all_auth - current_auth
  end

  # Get full feed
  def feed
    @feed = []

    authentications.each do |auth|
      @feed += FeedFactory.create(auth.provider.name, auth.token, auth.secret).feed
    end

    # Desc sort by created_at
    @feed.sort { |a,b| b[:created_at] <=> a[:created_at] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_filter :authenticate_user!

  def create
    omniauth = request.env["omniauth.auth"]
    current_user.add_auth omniauth
    redirect_to feed_path
  end

  # Delete auth
  def destroy
    Authentication.where(:user_id => current_user.id).destroy(params[:id])
    redirect_to :root
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    if user_signed_in?
      @auth = current_user.authentications
      render :auth_list
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/social_controller.rb
class SocialController < ApplicationController
  before_filter :authenticate_user!

  def index
    @feed = current_user.feed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  end

end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/social_helper.rb
module SocialHelper
end

app/views/index/auth_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Provider</th>
      <th>UID</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @auth.each do |a| %>
    <tr>
      <td><%= a.provider.name %></td>
      <td><%= a.uid %></td>
      <td><%= link_to "Delete", destroy_auth_path(a.id), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/index/index.html.erb
<h1>Hello! Please sign in to have access to awesome features!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aggregate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/components/navigation" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/components/_missing_providers.html.erb
<% current_user.missing_providers.each do |provider_name| %>
  <li><%= link_to "+#{provider_name.capitalize}", "/auth/#{provider_name}" %></li>
  <li class="divider-vertical"></li>
<% end %>

app/views/layouts/components/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Aggregate', root_path, :class => "brand" %>
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
          <% if user_signed_in? %>
            <ul class="nav">
              <li class="divider-vertical"></li>
              <% if current_user.authentications.any? %>
                <li><%= link_to "Feed", feed_path %></li>
                <li class="divider-vertical"></li>
              <% end %>
              <%= render "layouts/components/missing_providers" %>
            </ul>
          <% end %>
          <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</div>

app/views/social/_facebook_entry.html.erb
<div class="well entry facebook-entry">
  <div class="body">
    <div class="author">
      <%= link_to entry[:user_name], "https://facebook.com/#{entry[:user_id]}" %>
    </div>
    <% case entry[:type] %>
    <% when "link" %>
      <%= link_to entry[:name], entry[:link] %>
      <%= entry[:description] %>
    <% else %>
      <%= entry[:body] %>
    <% end %>
  </div>
  <div class="entry-footer">
    <span class="time">
      <%= entry[:created_at] %>
    </span>
  </div>
</div>

app/views/social/_twitter_entry.html.erb
<div class="well entry twitter-entry">
  <div class="body">
    <div class="author">
      <%= link_to "@#{entry[:screen_name]}", "https://twitter.com/#{entry[:screen_name]}" %>
    </div>
    <%= entry[:body] %>
  </div>
  <div class="entry-footer">
    <span class="time">
      <%= entry[:created_at] %>
    </span>
  </div>
</div>

app/views/social/_vkontakte_entry.html.erb
<div class="well entry vk-entry">
  <div class="body">
    <div class="author">
      <a href="<%= entry[:user][:link] %>"><%= entry[:user][:name] %></a>
    </div>
    <%= raw entry[:body] %>
  </div>
  <% entry[:attachments].each do |a| %>
    <div class="attachment">
      <% case a[:type] %>
      <% when :photo %>
        <%= image_tag a[:src] %>
      <% when :link %>
        <%= link_to a[:title], a[:url] %>
      <% end %>
    </div>
  <% end if entry[:attachments] %>
  <div class="entry-footer">
    <span class="time">
      <%= entry[:created_at] %>
    </span>
  </div>
</div>

app/views/social/index.html.erb
<div id="feed">
  <% @feed.each do |entry| %>
    <%= render :partial => "#{entry[:provider]}_entry", :locals => { :entry => entry } %>
  <% end %>
</div>